name: Full AWS Infra + Deploy Pipeline

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      TF_IN_AUTOMATION: true

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # Configure AWS credentials
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Terraform Init
      - name: Terraform Init
        working-directory: infra
        run: terraform init

      # Terraform Apply (creates EC2)
      - name: Terraform Apply
        working-directory: infra
        run: terraform apply -auto-approve

      # Capture EC2 IP
      - name: Get EC2 IP
        run: |
          echo "EC2_HOST=$(terraform output -raw ec2_public_ip)" >> $GITHUB_ENV

      # Setup SSH key
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/key.pem
          chmod 400 ~/.ssh/key.pem

      # Deploy Application via SSH
      - name: Deploy App to EC2
        run: |
          ssh -o StrictHostKeyChecking=no \
              -i ~/.ssh/key.pem \
              ${{ secrets.EC2_USER }}@${{ env.EC2_HOST }} << 'EOF'

            echo " Starting deployment..."

            # Install Docker + Git if missing
            if ! command -v docker &> /dev/null
            then
              sudo apt update -y
              sudo apt install -y docker.io git
              sudo systemctl start docker
              sudo systemctl enable docker
            fi

            sudo usermod -aG docker ubuntu || true

            # Clone repo
            cd /home/ubuntu
            if [ ! -d "cicd-tf-docker-aws" ]; then
              git clone https://github.com/Emprcode/cicd-tf-docker-aws.git
            fi

            cd cicd-tf-docker-aws/backend
            git pull origin main

            # Restart app
            docker stop smart-notes || true
            docker rm smart-notes || true

            docker build -t smart-notes-backend .

            docker run -d -p 5000:5000 \
              --name smart-notes \
              smart-notes-backend

            echo " Deployment completed"

          EOF