name: Deploy Backend to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            if [ ! -d "cicd-tf-docker-aws" ]; then
              git clone https://github.com/Emprcode/cicd-tf-docker-aws.git
            fi

            cd cicd-tf-docker-aws/backend

            git pull origin main

            docker stop smart-notes || true
            docker rm smart-notes || true

            docker build -t smart-notes-backend .

            docker run -d -p 5000:5000 \
              --env-file .env \
              --name smart-notes \
              smart-notes-backend